[build]
  command = "npm run netlify:build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22.19.0"
  NPM_VERSION = "10.9.3"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
